services:
  - type: web
    name: cashpot-v7-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://admin:admin123@cashpot-v7.abc123.mongodb.net/cashpot-v7?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: cashpot-v7-super-secret-key-2024-production